"""Add all portfolio tables

Revision ID: 452ebeb9b4eb
Revises: cdf971e3755d
Create Date: 2025-07-29 22:15:36.111124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452ebeb9b4eb'
down_revision = 'cdf971e3755d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
